#!/bin/sh

if [ -z $* ]
then
    echo "Usage: dkrun module.euo [DEPENDENCY]..." 1>&2
    echo "    Where all dependent modules must be listed explicitly," 1>&2
    echo "    after the module to typecheck." 1>&2
    exit 1
fi

main=$1
shift 1

echo "do t <- Dedukti.Runtime.start; main; Dedukti.Runtime.stop t" | ghci -x hs -XOverloadedStrings -fglasgow-exts $* $main
